### ISSUE TITLE
Broken Link? Other Initiatives : Teaching Kids

### ISSUE THREAD

**Issue by grokmann** [bridgefoundry/bridgefoundry.github.io#49]
The [Teaching Kids link](http://teachingkids.railsbridge.org/) under "Other Initiatives" in index.html appears to be broken. I couldn't find an updated link.

**Comment by ultrasaurus** [comment]
hmm... not totally surprised that heroku is failing since we haven't touched the site in FIVE YEARS!   Anyone want to turn this into a github pages site? just moved the repo from railsbridge -> bridgefoundry: https://github.com/bridgefoundry/teachingkids-site

**Comment by ultrasaurus** [comment]
Also, feel free to update the logo and other things.  As part of the re-factor, the Teaching Kids project is a Bridge Foundry project, rather than RailsBridge.  It was mostly Ruby and other kids-focused coding stuff, rather than Rails.

**Comment by ultrasaurus** [comment]
alternately, we could make it a category on the Bridge Foundry blog (then re-direct the old site to bridgefoundry.org/kids and create a page there that features the category of blog posts and resources) -- a bit more work, but maybe easier to maintain

cc @gregnokes

**Comment by audiodude** [comment]
I'd be willing to help with this, but it's hard without being able to see what the original content looked like.

Should I just fix it up and deploy to my own heroku instance in order to view it? Of course, if I do that, it might be ready to be redeployed to the existing site.

**Comment by ultrasaurus** [comment]
@audiodude added you to the 'teachingkids' app on heroku, if that helps.  I'm afraid all we've got now is the source code and misty memories...  I would just try to get it working locally.  The main goal would be to display the [posts](https://github.com/bridgefoundry/teachingkids-site/tree/master/src/_posts).  The lists of resources in [src](https://github.com/bridgefoundry/teachingkids-site/tree/master/src) are pretty short and could probably be consolidated.   It was basically a blog with a couple of content pages... which is why I thought it might make sense to simply add a category or something on the bridgefoundry blog and a page on the site.

Thanks so much for being willing to take this on!

**Comment by audiodude** [comment]
@ultrasaurus thanks for adding me, but I don't think it "took". I don't see the app in my Heroku dashboard, and I didn't receive any email that I had access.

I'll try to get it running locally.

**Comment by audiodude** [comment]
Okay I got it running locally. It looks really outdated....

**Comment by audiodude** [comment]
Okay I got the site running on Heroku again, after upgrading its stack. Agree that this should be integrated somehow with the main site, since it's all just jekyll.

http://teachingkids.railsbridge.org/
